metric: COCO
num_classes: 2

TrainDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: voc_train.json
  dataset_dir: /home/aistudio/PaddleDetection/dataset/Vehicle
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: voc_val.json
  dataset_dir: /home/aistudio/PaddleDetection/dataset/Vehicle
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: voc_test.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /home/aistudio/PaddleDetection/dataset/Vehicle # if set, anno_path will be 'dataset_dir/anno_path'
